Controllers/CategoriesController.cs
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rolodex.Data;
using Rolodex.Models;
using Rolodex.Services.Interfaces;

namespace Rolodex.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IEmailSender _emailService;
        private readonly ICategoryService _categoryService;

        public CategoriesController(UserManager<AppUser> userManager,
            IEmailSender emailService,
            ICategoryService categoryService)
        {
            _userManager = userManager;
            _emailService = emailService;
            _categoryService = categoryService;
        }

        // GET: Categories
        public async Task<IActionResult> Index(string? swalMessage = null)
        {
            // Pass along Sweet Alert message if there is one
            ViewData["SwalMessage"] = swalMessage;

            // get the user's categories
            string userId = _userManager.GetUserId(User)!;
            IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
            return View(categories);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Category category)
        {
            ModelState.Remove("AppUserId");

            if (!ModelState.IsValid)
            {
                return View(category);
            }

            try
            {
                category.AppUserId = _userManager.GetUserId(User);
                await _categoryService.AddCategoryAsync(category);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View(category);
            }
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            string userId = _userManager.GetUserId(User)!;

            Category? category = await _categoryService.GetUserCategoryByIdAsync(id, userId);
            if (category == null) return NotFound();

            return View(category);
        }

        // POST: Categories/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AppUserId,Name")] Category category)
        {
            if (id != category.Id) return NotFound();

            if (!ModelState.IsValid)
            {
                return View(category);
            }
            try
            {
                await _categoryService.UpdateCategoryAsync(category);

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            // two people are trying to edit the same category at the same time
            {
                if (!_categoryService.CategoryExists(category.Id)) return NotFound();
                else return View(category);
            }
            catch (Exception)
            {
                return View(category);
            }
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            string userId = _userManager.GetUserId(User)!;

            Category? category = await _categoryService.GetUserCategoryByIdAsync(id, userId);
            if (category == null) return NotFound();

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string userId = _userManager.GetUserId(User)!;

            Category? category = await _categoryService.GetUserCategoryByIdAsync(id, userId);

            // if user is attempting to delete a category that isn't theirs, return not found
            // otherwise, if the category exists and is theirs, delete
            if (category != null && category.AppUserId != userId) return NotFound();
            else if (category != null) await _categoryService.DeleteCategoryAsync(category);

            return RedirectToAction(nameof(Index));
        }

        // GET: Categories/EmailCategory/5
        public async Task<IActionResult> EmailCategory(int? id, string? swalMessage = null)
        {
            // Pass along Sweet Alert message if there is one
            ViewData["SwalMessage"] = swalMessage;

            if (id is null) return NotFound();

            string userId = _userManager.GetUserId(User)!;

            Category? category = await _categoryService.GetUserCategoryByIdAsync(id, userId);
            if (category == null) return NotFound();

            // Build list of contacts in that category
            List<Contact> emailContacts = new();
            emailContacts = category.Contacts.ToList();

            // build string containing the emails for each of those contacts
            StringBuilder stringBuilder = new();
            foreach (var contact in emailContacts)
            {
                stringBuilder.Append($"{contact.EmailAddress};");
            }
            //// remove final ; then build string
            stringBuilder.Remove(stringBuilder.ToString().Length - 1, 1);
            string? emailList = stringBuilder.ToString();

            // populate model
            EmailData model = new()
            {
                GroupName = category.Name,
                EmailAddress = emailList,
            };

            ViewData["EmailContacts"] = emailContacts;
            return View(model);
        }

        // POST: Categories/EmailCategory/5
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EmailCategory(EmailData model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string? email = model.EmailAddress!;
                    string? subject = model.EmailSubject;
                    string? htmlMessage = model.EmailBody;
                    await _emailService.SendEmailAsync(email!, subject!, htmlMessage!);

                    // Send SweetAlert for success
                    string? swalMessage = "Success: Email sent!";

                    return RedirectToAction(nameof(Index), new { swalMessage = swalMessage });
                }
                catch (Exception)
                {
                    // Send SweetAlert for failure
                    string? swalMessage = "Error: Email failed to send!";

                    return RedirectToAction(nameof(EmailCategory), new { swalMessage = swalMessage });
                    throw;
                }
            }
            return View(model);
        }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rolodex.Data;
using Rolodex.Models;
using Rolodex.Services;
using Rolodex.Services.Interfaces;

namespace Rolodex.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IImageService _imageService;
        private readonly ICategoryService _categoryService;
        private readonly INoteService _noteService;

        public NotesController(UserManager<AppUser> userManager,
            IImageService imageService,
            ICategoryService categoryService,
            INoteService noteService)
        {
            _userManager = userManager;
            _imageService = imageService;
            _categoryService = categoryService;
            _noteService = noteService;
        }

        // GET: Notes
        public async Task<IActionResult> Index(int? categoryId)
        {
            // get the user's notes
            string userId = _userManager.GetUserId(User)!;
            List<Note> notes = (await _noteService.GetUserNotesAsync(userId)).ToList();

            // and user's categories
            IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);

            // what will contain the filter result
            List<Note> model = new();

            // filter based on category
            if (categoryId is null) model = notes;
            else model = categories.SelectMany(c => c.Notes).ToList();

            // order
            model.OrderBy(n => n.Updated).ThenBy(n => n.Created);

            // provide the user's categories
            ViewData["CategoriesList"] = new SelectList(categories, "Id", "Name", categoryId);

            return View(model);
        }

        // GET: Filtered Contacts
        public async Task<IActionResult> SearchNotes(string? searchString)
        {
            // get the user's contacts
            string userId = _userManager.GetUserId(User)!;
            List<Note> notes = (await _noteService.GetUserNotesAsync(userId))
                .ToList();

            // what will contain the search result
            List<Note> model = new();

            // populate model with results
            if (string.IsNullOrEmpty(searchString)) model = notes;
            else model = notes.Where(c => c.NoteTitle!.ToLower().Contains(searchString.ToLower())
                || c.NoteText?.ToLower().Contains(searchString.ToLower()) == true)
                .OrderBy(n => n.Updated)
                    .ThenBy(n => n.Created)
                .ToList();

            // provide the user's categories as well
            IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
            ViewData["CategoriesList"] = new MultiSelectList(categories, "Id", "Name");

            // put the user's search into the ViewBag
            ViewData["SearchString"] = searchString;

            return View(nameof(Index), model);
        }

        // GET: Notes/Create
        public async Task<IActionResult> Create()
        {
            string userId = _userManager.GetUserId(User)!;

            IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
            ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name");

            return View();
        }

        // POST: Notes/Create
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoteTitle,Created,NoteText,AudioData,AudioType,ImageFile")] Note note, List<int> selected)
        {
            ModelState.Remove("AppUserId");

            if (!ModelState.IsValid)
            {
                string userId = _userManager.GetUserId(User)!;

                IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
                ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", selected);

                return View(note);
            }

            try
            {
                note.AppUserId = _userManager.GetUserId(User);
                note.Created = DateTime.Now;

                // Set Image data if one has been chosen
                if (note.ImageFile != null)
                {
                    // Convert file to byte array and assign it to image data
                    note.ImageData = await _imageService.ConvertFileToByteArrayAsync(note.ImageFile);
                    // Assign ImageType based on the chosen file
                    note.ImageType = note.ImageFile.ContentType;
                }

                await _noteService.AddNoteAsync(note);
                await _categoryService.AddCategoriesToNoteAsync(selected, note.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                string userId = _userManager.GetUserId(User)!;

                IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
                ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", selected);

                return View(note);
            }
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            string userId = _userManager.GetUserId(User)!;

            Note? note = await _noteService.GetNoteByIdAsync(id, userId);
            if (note == null) return NotFound();

            IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
            List<int> categoryIds = note.Categories.Select(n => n.Id).ToList();
            ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", categoryIds);

            return View(note);
        }

        // POST: Notes/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppUserId,NoteTitle,Created,Updated,NoteText,AudioData,AudioType,ImageData,ImageType,ImageFile")] Note note, List<int> selected)
        {
            if (id != note.Id) return NotFound();
            string userId = _userManager.GetUserId(User)!;

            ModelState.Remove("AppUserId");

            if (!ModelState.IsValid)
            {
                IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
                List<int> categoryIds = note.Categories.Select(n => n.Id).ToList();
                ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", categoryIds);

                return View(note);
            }

            try
            {
                note.AppUserId = _userManager.GetUserId(User);
                note.Updated = DateTime.Now;

                // Set Image data if one has been chosen
                if (note.ImageFile != null)
                {
                    // Convert file to byte array and assign it to image data
                    note.ImageData = await _imageService.ConvertFileToByteArrayAsync(note.ImageFile);
                    // Assign ImageType based on the chosen file
                    note.ImageType = note.ImageFile.ContentType;
                }

                await _noteService.UpdateNoteAsync(note);
                await _categoryService.AddCategoriesToNoteAsync(selected, note.Id);

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_noteService.NoteExists(note.Id)) return NotFound();
                else
                {

                    IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
                    List<int> categoryIds = note.Categories.Select(n => n.Id).ToList();
                    ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", categoryIds);

                    return View(note);
                }
            }
            catch (Exception)
            {
                IEnumerable<Category> categories = await _categoryService.GetUserCategoriesAsync(userId);
                List<int> categoryIds = note.Categories.Select(n => n.Id).ToList();
                ViewData["CategoryList"] = new MultiSelectList(categories, "Id", "Name", categoryIds);

                return View(note);
            }
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            string userId = _userManager.GetUserId(User)!;

            Note? note = await _noteService.GetNoteByIdAsync(id, userId);
            if (note == null) return NotFound();

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string userId = _userManager.GetUserId(User)!;

            Note? note = await _noteService.GetNoteByIdAsync(id, userId);

            // if user is attempting to delete a note that isn't theirs, return not found
            // otherwise, if the note exists and is theirs, delete
            if (note != null && note.AppUserId != userId) return NotFound();
            else if (note != null) await _noteService.DeleteNoteAsync(note);

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Rolodex</title>
    @*TO-DO: Update Metadata*@
    @*<meta name="description"
    content="Portfolio of projects, skills, and full-stack C# software development blog posts by Cadence Eva.">*@

    @*Favicon*@
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">

    @*Bootstrap*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
          crossorigin="anonymous">

    @*Bootstrap Icons*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    @*Devicons*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">

    @*Fonts*@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;500;600;700;800&family=Roboto:ital,wght@0,100;0,400;0,900;1,100;1,300;1,500;1,900&display=swap"
          rel="stylesheet">

    @*Custom Styling*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menupill.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/customForms.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Rolodex.styles.css" asp-append-version="true" />
</head>
<body>

    <div id="menuPillContainer" class="navbar navbar-dark">
        <nav id="menuPill" class="navbar-nav text-light">
            <div id="home-btn" class="nav-item">
                <a asp-controller="Home" asp-action="Index" class="nav-link"
                   data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="Home" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-house-fill"></i>
                    </div>
                    <span class="menu-label">Home</span>
                </a>
            </div>
            <div id="contacts-btn" class="nav-item">
                <a asp-controller="Contacts" asp-action="Index" class="nav-link"
                   data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="Contacts" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-people-fill"></i>
                    </div>
                    <span class="menu-label">Contacts</span>
                </a>
            </div>
            <div id="notes-btn" class="nav-item">
                <a asp-controller="Notes" asp-action="Index" class="nav-link"
                   data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="Notes" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-pencil-square"></i>
                    </div>
                    <span class="menu-label">Notes</span>
                </a>
            </div>
            <div id="categories-btn" class="nav-item">
                <a asp-controller="Categories" asp-action="Index" class="nav-link"
                   data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="Categories" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-tag-fill"></i>
                    </div>
                    <span class="menu-label">Categories</span>
                </a>
            </div>
            <div id="about-btn" class="nav-item">
                <a href="https://cadence-eva.netlify.app/" class="nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="About Me" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-info-circle-fill"></i>
                    </div>
                    <span class="menu-label">About Me</span>
                </a>
            </div>
            <div id="settings-btn" class="nav-item">
                <a asp-area="Identity" asp-page="/Account/Manage/Index" class="nav-link"
                   data-bs-toggle="tooltip" data-bs-placement="bottom"
                   data-bs-title="Settings" data-bs-custom-class="nav-tooltip">
                    <div class="icon-container">
                        <i class="bi bi-gear-fill"></i>
                    </div>
                    <span class="menu-label">Settings</span>
                </a>
            </div>
        </nav>
    </div>

    <main role="main" class="main-container">
        @RenderBody()
    </main>

    <footer class="footer container-fluid text-accent py-3">
        <div class="container">
            <div class="row row-cols-1 row-cols-lg-3 text-center align-items-center gy-2">
                <div class="col text-lg-start">
                    &copy2023 Cadence Eva Custin
                </div>
                <div class="col">
                    <img src="/img/Cadence-Eva-logo-transparent.png" width="300" alt="Cadence Eva Logo">
                </div>
                <div class="col text-lg-end">
                    <a class="text-decoration-none" href="https://www.linkedin.com/in/cadence-eva/">
                        <i class="bi bi-linkedin social-icons text-accent"></i>
                    </a>
                    <a class="text-decoration-none" href="https://github.com/eva-grimm">
                        <i class="bi bi-github social-icons"></i>
                    </a>
                    <a class="text-decoration-none" href="mailto:eva.custin@gmail.com">
                        <i class="bi bi-envelope-at social-icons"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @*Bootstrap*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    @*Sweet Alerts*@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
</body>
</html>